theme: jekyll-theme-cayman
title: Sunes Hjemmeside
description: Welkommen til min hjemmeside. Jeg er 21 år gammel og er igang med at læse til datamatiker ved Zealand i Næstved.
image: ![me](https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-9/42608042_10209743623106422_538400714926325760_n.jpg?_nc_cat=102&_nc_oc=AQm3v_1ZApuLs-4gE0gQMGa1QIadl05p0q6gMym9L3vZqHPzYpNPryAhhRhScx2gJLk&_nc_ht=scontent-frx5-1.xx&oh=afebd28ebc3a42d2b21f632908e12d1a&oe=5E0A2F48
